#!/usr/bin/env bash

CURRENT_TIME=$(date "+%Y%m%d-%H%M%S")
FILE_NAME=$1$CURRENT_TIME'.sql'

echo "First I'll need your MySQL root user password to back up your database."
read -sp 'Password: ' PASSVAR

mkdir -p /var/www/archive
mysqldump -uroot -p$PASSVAR $1 > /var/www/archive/$FILE_NAME