#!/bin/bash

# from: http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/

# Functions
. /opt/lempdash/library/functions

EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`
 
Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="GRANT ALL ON $1.* TO '$2'@'localhost' IDENTIFIED BY '$3';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"
 
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname dbuser dbpass"
  exit $E_BADARGS
fi

prompt "I'll need your MySQL root user password next."

$MYSQL -uroot -p -e "$SQL"

ok "MySQL database '$1' is created."
ok "Assigned user '$2' with the password '$3'"
echo
greet "You're welcome."