#!/bin/bash

# from: http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/

# Functions
. /opt/lempdash/library/functions

EXPECTED_ARGS=1
E_BADARGS=65
MYSQL=`which mysql`
 
Q1="DROP USER '$1'@'localhost';"
Q2="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}"
 
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbuser"
  exit $E_BADARGS
fi

echo "I'll need your MySQL root user password next."

$MYSQL -uroot -p -e "$SQL"

ok "MySQL user '$1' is dead, Jim."