#!/bin/bash

# from: http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/

# Functions
. /opt/lempdash/library/functions

WEB_DIR='/var/www'
MYSQL=`which mysql`
CURRENT_TIME=$(date "+%Y%m%d-%H%M%S")
FILE_NAME=$1$CURRENT_TIME'.sql'
 
Q1="DROP DATABASE IF EXISTS $1;"
SQL="$Q1"
 
prompt "First I'll need your MySQL root user password to backup your database."
read -sp 'Password: ' PASSVAR

echo

mkdir -p /var/www/archive
mysqldump -uroot -p$PASSVAR $1 > /var/www/archive/$FILE_NAME

$MYSQL -uroot -p$PASSVAR -e "$SQL"

rc=$?; 
if [[ $rc != 0 ]]; then 
	echo "You sure your password is correct?"
else
	ok "MySQL database '$1' is removed and archived at $WEB_DIR/archive/$FILE_NAME"
fi