#!/bin/bash
# from: http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/
EXPECTED_ARGS=2
E_BADARGS=65
MYSQL=`which mysql`
 
Q1="DROP DATABASE IF EXISTS $1;"
Q2="DROP USER '$2'@'localhost';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}"
 
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname dbuser"
  exit $E_BADARGS
fi

echo "I'll need your MySQL root user password next."

$MYSQL -uroot -p -e "$SQL"