#!/usr/bin/env bash
# LEMPDash Install script
# Must be run with sudo priviliges

# Variables

# Make task scripts executlable
chmod +x lempdash
find ./tasks/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;

# Copy all the things into bin

mkdir -p /opt/lempdash/tasks
cp -R tasks /opt/lempdash/tasks/
cp lempdash /bin/ldash

