#!/usr/bin/env bash
# LEMPDash Install script
# Must be run with sudo priviliges

# Variables

# Check dependencies for mission critical stuff
type zip >/dev/null 2>&1 || echo "The package 'zip' is not installed on your system, so installing..." && apt-get install zip

# Copy all the things into bin

mkdir -p /opt/lempdash/tasks
cp -R tasks /opt/lempdash
cp lempdash /bin/ldash

# Make task scripts executlable
chmod +x /bin/ldash
find /opt/lempdash/tasks/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;