#!/usr/bin/env bash

echo "Hi! I'm LEMPDASH"

if [ $1 == "cr" ]; then
	if [ $2 == "site" ]; then	
	echo "Yeah, let's do this!"
		if [ $# == 3 ]; then
			echo "Creating site..." $3	
			/opt/lempdash/tasks/nginx/createblock "$3"
		fi
	fi	
elif [ $1 == "rm" ]; then
	echo "Ok, grim reaper, thy will be done."
	if [ $2 == "site" ]; then
		if [ $# == 3 ]; then	
			echo "Removing site..." $3	
			/opt/lempdash/tasks/nginx/removeblock "$3"
		fi
	fi
fi

exit 10