#!/usr/bin/env bash
# LEMPDash Upgrade script
# Must be run with root priviliges

# Copy all the things into /bin and /opt
mkdir -p /opt/lempdash/tasks
cp -R tasks /opt/lempdash
cp lempdash /bin/ldash

# Make task scripts executlable
chmod +x /bin/ldash
find /opt/lempdash/tasks/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;

