#!/usr/bin/env bash
# LEMPDash Install script
# Must be run with sudo priviliges

# Make task scripts executlable
chmod +x lempdash
find ./tasks/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;

# Copy all the things

cp -R tasks /opt/lempdash
cp lempdash /bin/ldash

