#!/bin/bash

# LEMPDash Upgrade script

# Copy all the things into /bin and /opt
mkdir -p /opt/lempdash/tasks
cp -R tasks /opt/lempdash
cp -R library /opt/lempdash
cp lempdash /bin/ldash

# Make task scripts executlable
chmod +x /bin/ldash
find /opt/lempdash/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;

