#!/bin/bash

# Functions
. /opt/lempdash/library/functions

# Variables
NGINX_AVAILABLE_VHOSTS='/etc/nginx/sites-available'
ARCHIVE_DIR='/var/www/archive'
CURRENT_TIME=$(date "+%Y%m%d-%H%M%S")
FILE_NAME="nginx_serverblock_"$CURRENT_TIME"_"$1

cp $NGINX_AVAILABLE_VHOSTS/$1 $ARCHIVE_DIR/$1/$FILE_NAME

rc=$?; 
if [[ $rc != 0 ]]; then 
	note_perms $ARCHIVE_DIR
else
	ok "Server block '$1' is archived at $ARCHIVE_DIR/$1/$FILE_NAME"
fi